### ISSUE TITLE
.Net Core Version: "SEHException (0x80004005): External component has thrown an exception."

### ISSUE THREAD

**Issue by erdomke** [erdomke/InnovatorAdmin#225]
When launching the application, the following error is thrown for some users:

```
System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at System.Windows.Forms.UnsafeNativeMethods.ThemingScope.DeactivateActCtx(Int32 dwFlags, IntPtr lpCookie)
   at System.Windows.Forms.UnsafeNativeMethods.ThemingScope.Deactivate(IntPtr userCookie)
   at System.Windows.Forms.Control.CreateHandle()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.ControlCollection.Add(Control value)
   at System.Windows.Forms.TableLayoutControlCollection.Add(Control control, Int32 column, Int32 row)
   at InnovatorAdmin.EditorWindow.InitializeComponent() in D:\ANSYSDev\Code\GitHub\InnovatorAdmin\InnovatorAdmin\Ide\EditorWindow.Designer.cs:line 1212
   at InnovatorAdmin.EditorWindow..ctor() in D:\ANSYSDev\Code\GitHub\InnovatorAdmin\InnovatorAdmin\Ide\EditorWindow.cs:line 101
   at InnovatorAdmin.Program.Main(String[] args) in D:\ANSYSDev\Code\GitHub\InnovatorAdmin\InnovatorAdmin\Program.cs:line 48
```

**Comment by deeprobin** [comment]
Can confirm this error, but cannot reproduce
